# Generated by Django 4.2.5 on 2023-10-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_request",
            field=models.DateTimeField(
                blank=True,
                help_text="Stores the timestamp of the last request made by a user.",
                null=True,
            ),
        ),
    ]
